### ISSUE TITLE
[Question] What if Alice is offline?

### ISSUE THREAD

**Issue by katopz** [lightstreams/lightstreams#3]
![image](https://user-images.githubusercontent.com/97060/32427294-40054644-c2f2-11e7-9756-859e2f59d3e2.png)

In this situation it work because Alice is online right?
What happen if Alice is off?
Did Alice need to be online 24/7 to provide her content? (Like P2P?)

Thanks

**Comment by mikesmo** [comment]
Fantastic question! Alice will be using an installable application on her desktop computer. She will have two options:
1) Keep her client connected to the network until other users start sharing (much like p2p services today)
2) Other users on the network are incentivised to be 'host' nodes. The artist can pay a small fee to them to host the file for a short time until they get traction.

**Comment by katopz** [comment]
Thanks, I'll continue conversation via telegram :)
